### ISSUE TITLE
Exception in handler for D-Bus signal

### ISSUE THREAD

**Issue by notroj** [InfrastructureServices/dnsconfd#66]
dnsconfd-1.4.1-1.fc40.noarch

```
Oct 10 07:50:26 NetworkManager[2627]: <info>  [1728543026.0955] device (tun0): state change: unmanaged -> unavailable (reason 'connection-assumed', sys-iface-state: '>
Oct 10 07:50:26 NetworkManager[2627]: <info>  [1728543026.0966] device (tun0): state change: unavailable -> disconnected (reason 'connection-assumed', sys-iface-state>
Oct 10 07:50:26 NetworkManager[2627]: <info>  [1728543026.0971] device (tun0): Activation: starting connection 'tun0' (4a934136-3f0a-4856-bd4a-51d9d9cafe4b)
Oct 10 07:50:26 NetworkManager[2627]: <info>  [1728543026.0974] device (tun0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'external')
Oct 10 07:50:26 NetworkManager[2627]: <info>  [1728543026.0975] device (tun0): state change: prepare -> config (reason 'none', sys-iface-state: 'external')
Oct 10 07:50:26 NetworkManager[2627]: <info>  [1728543026.0976] device (tun0): state change: config -> ip-config (reason 'none', sys-iface-state: 'external')
Oct 10 07:50:26 NetworkManager[2627]: <info>  [1728543026.0979] device (tun0): state change: ip-config -> ip-check (reason 'none', sys-iface-state: 'external')
Oct 10 07:50:26 dnsconfd[2718]: INFO:DnsconfdContext:New state: ContextState.SUBSCRIBING_NM_CONNECTIONS, new event: SUCCESS
Oct 10 07:50:26 dnsconfd[2718]: INFO:DnsconfdContext:New state: ContextState.CHECK_ALL_CONNECTIONS_UP, new event: SUCCESS
Oct 10 07:50:26 dnsconfd[2718]: INFO:Running:Successfully gathered connections
Oct 10 07:50:26 dnsconfd[2718]: INFO:DnsconfdContext:New state: ContextState.GATHER_CONN_CONFIG, new event: SUCCESS
Oct 10 07:50:26 systemd[1]: Starting NetworkManager-dispatcher.service - Network Manager Script Dispatcher Service...
Oct 10 07:50:26 dnsconfd[2718]: INFO:Running:Successfully subscribed to ip changes
Oct 10 07:50:26 dnsconfd[2718]: INFO:DnsconfdContext:New state: ContextState.SUBSCRIBE_IP_CHANGES, new event: SUCCESS
Oct 10 07:50:26 dnsconfd[2718]: INFO:Running:At least one ip object is ready for routing, proceeding
Oct 10 07:50:26 dnsconfd[2718]: INFO:DnsconfdContext:New state: ContextState.CHECK_IP_OBJECTS, new event: SUCCESS
Oct 10 07:50:26 dnsconfd[2718]: INFO:RoutingManager:Commencing route check
Oct 10 07:50:26 dnsconfd[2718]: INFO:RoutingManager:Checking routing for server 1.2.3.254
Oct 10 07:50:26 dnsconfd[2718]: INFO:RoutingManager:Server is in the same network as interface, routing not needed
Oct 10 07:50:26 dnsconfd[2718]: INFO:RoutingManager:Checking routing for server 2001:...:1
Oct 10 07:50:26 dnsconfd[2718]: INFO:RoutingManager:Server is in the same network as interface, routing not needed
Oct 10 07:50:26 dnsconfd[2718]: INFO:RoutingManager:Checking routing for server 1.2.3.254
Oct 10 07:50:26 dnsconfd[2718]: ERROR:dbus.connection:Exception in handler for D-Bus signal:
Oct 10 07:50:26 dnsconfd[2718]: Traceback (most recent call last):
Oct 10 07:50:26 dnsconfd[2718]:   File "/usr/lib64/python3.12/site-packages/dbus/connection.py", line 218, in maybe_handle_message
Oct 10 07:50:26 dnsconfd[2718]:     self._handler(*args, **kwargs)
Oct 10 07:50:26 dnsconfd[2718]:   File "/usr/lib/python3.12/site-packages/dnsconfd/routing_manager.py", line 256, in <lambda>
Oct 10 07:50:26 dnsconfd[2718]:     cb = lambda dbus_int, props, invalid: self._on_ip_obj_change(serial,
Oct 10 07:50:26 dnsconfd[2718]:                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 10 07:50:26 dnsconfd[2718]:   File "/usr/lib/python3.12/site-packages/dnsconfd/routing_manager.py", line 215, in _on_ip_obj_change
Oct 10 07:50:26 dnsconfd[2718]:     self.transition_function(event)
Oct 10 07:50:26 dnsconfd[2718]:   File "/usr/lib/python3.12/site-packages/dnsconfd/fsm/dnsconfd_context.py", line 85, in transition_function
Oct 10 07:50:26 dnsconfd[2718]:     event = callback(event)
Oct 10 07:50:26 dnsconfd[2718]:             ^^^^^^^^^^^^^^^
Oct 10 07:50:26 dnsconfd[2718]:   File "/usr/lib/python3.12/site-packages/dnsconfd/fsm/transitions/running.py", line 203, in _modify_connections
Oct 10 07:50:26 dnsconfd[2718]:     routed_servers, change = self.route_mgr.handle_routes_process()
Oct 10 07:50:26 dnsconfd[2718]:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 10 07:50:26 dnsconfd[2718]:   File "/usr/lib/python3.12/site-packages/dnsconfd/routing_manager.py", line 502, in handle_routes_process
Oct 10 07:50:26 dnsconfd[2718]:     present_specific_route["next-hop"]))
Oct 10 07:50:26 dnsconfd[2718]:     ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
Oct 10 07:50:26 dnsconfd[2718]: KeyError: 'next-hop'
```

**Comment by notroj** [comment]
Confirmed this is fixed in #67
